SELECT				
	NP_T_INPUT_COMMON.HINMOKU_CD			
	,NP_T_INPUT_COMMON.LOT_NO			
	,NP_T_INPUT_ITAATSU.SOKUTEI_AVG			
	,NP_T_INPUT_ITAATSU.UPPER_REF_VAL			
	,NP_T_INPUT_ITAATSU.LOWER_REF_VAL	
	,NP_T_INPUT_ITAATSU.CREATED_DATE
	,NP_T_INPUT_ITAATSU.CREATED_BY
	,NP_T_INPUT_ITAATSU.CREATED_PRG_NM
	,NP_T_INPUT_ITAATSU.UPDATED_DATE
	,NP_T_INPUT_ITAATSU.UPDATED_BY
	,NP_T_INPUT_ITAATSU.UPDATED_PRG_NM
	,NP_T_INPUT_ITAATSU.MODIFY_COUNT
FROM NP_T_INPUT_ITAATSU
INNER JOIN (
	SELECT DISTINCT
		LOT_NO, HINMOKU_CD
	FROM NP_T_INPUT_COMMON
) NP_T_INPUT_COMMON
	ON NP_T_INPUT_ITAATSU.LOT_NO = NP_T_INPUT_COMMON.LOT_NO			
