SELECT
	NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.HINMOKU_CD
	,NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.LOT_NO
	,NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.KBN
	,NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.ITAATSU
	,NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.BIKO
	,NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.CHK_JOGAI
	,NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.CREATED_DATE
	,NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.CREATED_BY
	,CREATED.USER_NM AS CREATED_NM
	,NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.CREATED_PRG_NM
	,NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.UPDATED_DATE
	,NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.UPDATED_BY
	,UPDATED.USER_NM AS UPDATED_NM
	,NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.UPDATED_PRG_NM
	,NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.MODIFY_COUNT
FROM
	NP_T_INPUT_ITAATSU_HINMOKU_MEISAI
LEFT OUTER JOIN TLN_M_USER CREATED
	ON CREATED.USER_ID = NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.CREATED_BY
LEFT OUTER JOIN TLN_M_USER UPDATED
	ON UPDATED.USER_ID = NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.UPDATED_BY
WHERE
	NP_T_INPUT_ITAATSU_HINMOKU_MEISAI.KBN = '090'