SELECT
	SIYO_SEIZO_JKN_MEISAI2.SIYOSYO_SEQ -- PK HIDDEN
	,SIYO_SEIZO_JKN_MEISAI2.KOUTEI_SEQ -- PK HIDDEN
	,SIYO_SEIZO_JKN_MEISAI2.GYOSU -- PK 行数
	,'L' + CONVERT(NVARCHAR, SIYO_SEIZO_JKN_MEISAI2.GYOSU + 1 ) AS LAYER
	,SIYO_SEIZO_JKN_MEISAI2.DATA01 -- 備考
	,SIYO_SEIZO_JKN_MEISAI2.TOKUSYU_JOKEN
FROM
	SIYO_SEIZO_JKN_MEISAI2
WHERE
	SIYO_SEIZO_JKN_MEISAI2.SIYOSYO_SEQ = /**%SIYOSYO_SEQ%**/NULL
AND SIYO_SEIZO_JKN_MEISAI2.KOUTEI_SEQ = /**%KOUTEI_SEQ%**/NULL