SELECT
	SIYO_SEIZO_JKN_MEISAI.SIYOSYO_SEQ -- PK HIDDEN
	,SIYO_SEIZO_JKN_MEISAI.KOUTEI_SEQ -- PK HIDDEN
	,SIYO_SEIZO_JKN_MEISAI.GYOSU -- PK 行数
	,SIYO_SEIZO_JKN_MEISAI.DATA01 -- 備考
FROM
	SIYO_SEIZO_JKN_MEISAI
WHERE
	SIYO_SEIZO_JKN_MEISAI.SIYOSYO_SEQ = /**%SIYOSYO_SEQ%**/NULL
AND SIYO_SEIZO_JKN_MEISAI.KOUTEI_SEQ = /**%KOUTEI_SEQ%**/NULL