SELECT
	LOT_NO
	,HINMOKU.HINMOKU_CD
	,ITAATSU
	,SIYO_090_ITA_FROM
	,SIYO_090_ITA_TO
	,ITA_090_FROM
	,ITA_090_TO
	,ITA090_CNT
	,ITAATSU2
	,SIYO_091_ITA_FROM
	,SIYO_091_ITA_TO
	,ITA_091_FROM
	,ITA_091_TO
	,ITA091_CNT
	,CREATED_DATE
	,CREATED_BY
	,CREATED_PRG_NM
	,UPDATED_DATE
	,UPDATED_BY
	,UPDATED_PRG_NM
	,MODIFY_COUNT
	,SIYOSYO_SEQ
	,KOUTEI_091.CNT
FROM
	NP_T_INPUT_ITAATSU_LOT_HEADER
OUTER APPLY (
	SELECT TOP 1
		HINMOKU_CD
		,SIYOSYO_SEQ
	FROM
		O7ISCHEDULE
	WHERE
		LOT_NO = NP_T_INPUT_ITAATSU_LOT_HEADER.LOT_NO
) HINMOKU

OUTER APPLY (

	SELECT TOP 1

		COUNT(*) AS CNT
	FROM
		KOUTEIJUN_KANRI
	WHERE
		SIYOSYO_SEQ = HINMOKU.SIYOSYO_SEQ
	AND KOUTEI_CD = '091'

) KOUTEI_091