SELECT 
	NP_T_PRESS_STRUCT_SINGLE.PID
	,NP_T_PRESS_STRUCT_SINGLE.PRESS_NO
	,NP_T_PRESS_STRUCT_SINGLE.SEIKEI_JOKEN
	,NP_T_PRESS_STRUCT_SINGLE.PRESS_TYPE
	,NP_T_PRESS_STRUCT_SINGLE.COUNT
	,NP_T_PRESS_STRUCT_SINGLE.SET_DATE
	,NP_T_PRESS_STRUCT_SINGLE.SET_SAKUSEISYA_CD_GU_SUU
	,GU_SUU.USER_NM AS SET_SAKUSEISYA_GU_SUU
	,NP_T_PRESS_STRUCT_SINGLE.KOSEIHYO_SAKUSEISYA_CD1
	,KOSEIHYO_SAKUSEISYA1.USER_NM AS KOSEIHYO_SAKUSEISYA1
	,NP_T_PRESS_STRUCT_SINGLE.BIKO
	,NP_T_PRESS_STRUCT_SINGLE.SET_SAKUSEISYA_CD_KI_SUU
	,KI_SUU.USER_NM AS SET_SAKUSEISYA_CD_SUU
	,NP_T_PRESS_STRUCT_SINGLE.KOSEIHYO_SAKUSEISYA_CD2
	,KOSEIHYO_SAKUSEISYA2.USER_NM AS KOSEIHYO_SAKUSEISYA2
	,NP_T_PRESS_STRUCT_SINGLE.SET_SAKUSEISYA_CD
	,SET_SAKUSEISYA.USER_NM AS SET_SAKUSEISYA
	,NP_T_PRESS_STRUCT_SINGLE.PACKING_SAGYOSYA_CD
	,PACKING_SAGYOSYA.USER_NM AS PACK_USER_NM
	,NP_T_PRESS_STRUCT_SINGLE.START_DT
	,NP_T_PRESS_STRUCT_SINGLE.START_TIME
	,NP_T_PRESS_STRUCT_SINGLE.TEMPRETURE
	,NP_T_PRESS_STRUCT_SINGLE.HUMIDITY
	,NP_T_PRESS_STRUCT_SINGLE.NO_1
	,NP_T_PRESS_STRUCT_SINGLE.NO_2
	,NP_T_PRESS_STRUCT_SINGLE.NO_3
	,NP_T_PRESS_STRUCT_SINGLE.NO_4
	,NP_T_PRESS_STRUCT_SINGLE.NO_5
	,NP_T_PRESS_STRUCT_SINGLE.NO_6
	,NP_T_PRESS_STRUCT_SINGLE.NO_7
	,NP_T_PRESS_STRUCT_SINGLE.NO_8
	,NP_T_PRESS_STRUCT_SINGLE.NO_9
	,NP_T_PRESS_STRUCT_SINGLE.NO_10
	,dbo.RITA_PRESS_WORK_SIZE('1', PID) AS NO_1_WORK_SIZE
	,dbo.RITA_PRESS_WORK_SIZE('2', PID) AS NO_2_WORK_SIZE
	,dbo.RITA_PRESS_WORK_SIZE('3', PID) AS NO_3_WORK_SIZE
	,dbo.RITA_PRESS_WORK_SIZE('4', PID) AS NO_4_WORK_SIZE
	,dbo.RITA_PRESS_WORK_SIZE('5', PID) AS NO_5_WORK_SIZE
	,dbo.RITA_PRESS_WORK_SIZE('6', PID) AS NO_6_WORK_SIZE
	,dbo.RITA_PRESS_WORK_SIZE('7', PID) AS NO_7_WORK_SIZE
	,dbo.RITA_PRESS_WORK_SIZE('8', PID) AS NO_8_WORK_SIZE
	,dbo.RITA_PRESS_WORK_SIZE('9', PID) AS NO_9_WORK_SIZE
	,dbo.RITA_PRESS_WORK_SIZE('10', PID) AS NO_10_WORK_SIZE
	,NP_T_PRESS_STRUCT_SINGLE.CREATED_DATE
	,NP_T_PRESS_STRUCT_SINGLE.CREATED_BY
	,NP_T_PRESS_STRUCT_SINGLE.CREATED_PRG_NM
	,NP_T_PRESS_STRUCT_SINGLE.UPDATED_DATE
	,NP_T_PRESS_STRUCT_SINGLE.UPDATED_BY
	,NP_T_PRESS_STRUCT_SINGLE.UPDATED_PRG_NM
	,NP_T_PRESS_STRUCT_SINGLE.MODIFY_COUNT
	,FORMAT(NP_T_PRESS_STRUCT_SINGLE.SET_DATE,'yyyy年MM月dd日(ddd)') AS EXCEL_OUT_SET_DATE
	,FORMAT(NP_T_PRESS_STRUCT_SINGLE.START_DT,'yyyy年MM月dd日(ddd)') AS EXCEL_OUT_START_DT
	,FORMAT(NP_T_PRESS_STRUCT_SINGLE.START_DT,'yyyy/MM/dd') AS EXCEL_OUT_START_DT2
	,CASE 
		WHEN NP_T_PRESS_STRUCT_SINGLE.START_TIME IS NOT NULL 
		THEN CONCAT(
			LEFT(NP_T_PRESS_STRUCT_SINGLE.START_TIME, 2), '時',
			SUBSTRING(NP_T_PRESS_STRUCT_SINGLE.START_TIME, 4, 2), '分'
		)
		ELSE NULL
	END AS EXCEL_OUT_START_TIME
FROM
	NP_T_PRESS_STRUCT_SINGLE
LEFT OUTER JOIN COM_M_USER GU_SUU
	ON GU_SUU.USER_ID = NP_T_PRESS_STRUCT_SINGLE.SET_SAKUSEISYA_CD_GU_SUU
LEFT OUTER JOIN COM_M_USER KOSEIHYO_SAKUSEISYA1
	ON KOSEIHYO_SAKUSEISYA1.USER_ID = NP_T_PRESS_STRUCT_SINGLE.KOSEIHYO_SAKUSEISYA_CD1
LEFT OUTER JOIN COM_M_USER KI_SUU
	ON KI_SUU.USER_ID = NP_T_PRESS_STRUCT_SINGLE.SET_SAKUSEISYA_CD_KI_SUU
LEFT OUTER JOIN COM_M_USER KOSEIHYO_SAKUSEISYA2
	ON KOSEIHYO_SAKUSEISYA2.USER_ID = NP_T_PRESS_STRUCT_SINGLE.KOSEIHYO_SAKUSEISYA_CD2
LEFT OUTER JOIN COM_M_USER SET_SAKUSEISYA
	ON SET_SAKUSEISYA.USER_ID = NP_T_PRESS_STRUCT_SINGLE.SET_SAKUSEISYA_CD
LEFT OUTER JOIN COM_M_USER PACKING_SAGYOSYA
	ON PACKING_SAGYOSYA.USER_ID = NP_T_PRESS_STRUCT_SINGLE.PACKING_SAGYOSYA_CD