.SELECT 
	ID
	,PID
	,POSITION_FROM
	,POSITION_TO
	,P_SLASH_P
	,COMBINE
	,SPEC
	,SIYOSYO_NO
	,SIYOSYO_SEQ
	,SO_SUU
	,HINMOKU_CD
	,HINMOKU_NM
	,SAGYO_KU
	,LOT_NO
	,SIAGE_ITAATSU
	,WORK_SIZE
	,SEIHIN_KO_KEI_SIZE_YOKO
	,SEIHIN_KO_KEI_SIZE_TATE
	,MAISUU
	,GAISOUBAN
	,KASANE_SUU
	,ROUND(SAGYO_M2_SUU,2) AS SAGYO_M2_SUU --作業㎡数
	,SAGYO_PN_SUU --作業PN数
	,GOUKAKU_PN_SUU --合格PN数
	,FURYO_PN_SUU --不良PN数
	,SAGYO_PCS_SUU
	,GOUKAKU_PCS_SUU
	,FURYO_PCS_SUU
	,WF_KUMI_SUU
	,NAISO_LINE_HABA
	,ANA_AKE_SUU
	,GAISO_LINE_HABA
	,MENTUKE_SUU
	,SEIHIN_SIZE_L
	,SEIHIN_SIZE_M
	,UL_NO
	,SINKI_KBN
	,HYOMEN_SYORI
	,TORISUU_M2
	,ET_DOUATSU
	,ET_SPEED
	,LINE_HABA
	,KIZAI_DOUHAKU_ATSU
	,SITEI_MEKKI_ATSU
	,DENRYU_MITSUDO
	,RIRON_MEKKI_ATSU_MAX
	,RIRON_MEKKI_ATSU_MIN
	,RIRON_MEKKI_ATSU_AVE
	,START_DT
	,START_JIKAN
	,BEFORE_KOUTEI_JUN
	,BEFORE_KOUTEI_CD
	,CURRENT_KOUTEI_JUN
	,CURRENT_KOUTEI_CD
	,NEXT_KOUTEI_JUN
	,NEXT_KOUTEI_CD
	,GOUKAKU_M2_SUU
	,ROUND(PRESS_M2_SUU,2) AS PRESS_M2_SUU
	,MODIFY_COUNT
FROM
	NP_T_INPUT_COMMON
WHERE
	PID = /**%PID%**/''