SELECT
	NP_T_PRESS_STRUCT_SINGLE.PID
	,NP_T_PRESS_STRUCT_SINGLE.PRESS_TYPE
	,NP_T_PRESS_STRUCT_SINGLE.COUNT
	,NP_T_PRESS_STRUCT_SINGLE.SET_DATE
	,NP_T_PRESS_STRUCT_SINGLE.START_DT
	,NP_T_PRESS_STRUCT_SINGLE.START_TIME
	,NP_T_PRESS_STRUCT_SINGLE.OBIC_HOKOKU_SAGYO_DT
	,NP_T_PRESS_STRUCT_SINGLE.OBIC_HOKOKU_SAGYO_TIME
	,NP_T_PRESS_STRUCT_SINGLE.SEIKEI_JOKEN
	,NP_T_PRESS_STRUCT_SINGLE.MENATSU
	,NP_T_PRESS_STRUCT_SINGLE.OBIC_HOKOKU_TNT_CD
	,SAGYO_SYA.USER_NM
	,NP_T_PRESS_STRUCT_SINGLE.PACKING_SAGYOSYA_CD
	,PACKING_SAGYOSYA.USER_NM AS PACK_USER_NM
	,NP_T_PRESS_STRUCT_SINGLE.BIKO
	,NP_T_PRESS_STRUCT_SINGLE.MODIFY_COUNT
FROM
	NP_T_PRESS_STRUCT_SINGLE
LEFT OUTER JOIN COM_M_USER SAGYO_SYA
	ON SAGYO_SYA.USER_ID = NP_T_PRESS_STRUCT_SINGLE.OBIC_HOKOKU_TNT_CD
LEFT OUTER JOIN COM_M_USER PACKING_SAGYOSYA
	ON PACKING_SAGYOSYA.USER_ID = NP_T_PRESS_STRUCT_SINGLE.PACKING_SAGYOSYA_CD