SELECT
	ID
	,PID
	,HINMOKU_CD
	,HINMOKU_NM
	,SAGYO_KU
	,LOT_NO
	,SAGYO_PCS_SUU
	,GOUKAKU_PCS_SUU
	,FURYO_PCS_SUU
	,ITAATSU
	,SIYO_090_ITA_FROM
	,SIYO_090_ITA_TO
	,CASE
		WHEN SIYO_090_ITA_FROM IS NULL THEN NULL
		WHEN SIYO_090_ITA_FROM <= ITAATSU AND ITAATSU <= SIYO_090_ITA_TO THEN '0'
		ELSE '1'
	END AUTO_090
	,GIJUTU_090
	,ITAATSU2
	,SIYO_091_ITA_FROM
	,SIYO_091_ITA_TO
	,CASE
		WHEN SIYO_091_ITA_FROM IS NULL THEN NULL
		WHEN SIYO_091_ITA_FROM <= ITAATSU2 AND ITAATSU2 <= SIYO_091_ITA_TO THEN '0'
		ELSE '1'
	END AUTO_091
	,GIJUTU_091
FROM (

	SELECT 
		NP_T_INPUT_COMMON.ID
		,NP_T_INPUT_COMMON.PID
		,NP_T_INPUT_COMMON.HINMOKU_CD
		,NP_T_INPUT_COMMON.HINMOKU_NM
		,NP_T_INPUT_COMMON.SAGYO_KU
		,NP_T_INPUT_COMMON.LOT_NO
		,NP_T_INPUT_COMMON.SAGYO_PCS_SUU
		,NP_T_INPUT_COMMON.GOUKAKU_PCS_SUU
		,NP_T_INPUT_COMMON.FURYO_PCS_SUU
		,NP_T_INPUT_ITAATSU_LOT_HEADER.ITAATSU
		,CASE
			WHEN ITA090_CNT > 5 THEN ITA_090_FROM
			ELSE ISNULL(NP_T_INPUT_ITAATSU_LOT_HEADER.SIYO_090_ITA_FROM, KIJUN_090.DATA01)
		END SIYO_090_ITA_FROM
		,CASE
			WHEN ITA090_CNT > 5 THEN ITA_090_TO
			ELSE ISNULL(NP_T_INPUT_ITAATSU_LOT_HEADER.SIYO_090_ITA_TO, KIJUN_090.DATA02)
		END SIYO_090_ITA_TO
		,NP_T_INPUT_ITAATSU_LOT_HEADER.GIJUTU_090
		,NP_T_INPUT_ITAATSU_LOT_HEADER.ITAATSU2

		,CASE
			WHEN ITA091_CNT > 5 THEN ITA_091_FROM
			ELSE ISNULL(NP_T_INPUT_ITAATSU_LOT_HEADER.SIYO_091_ITA_FROM, KIJUN_091.DATA01)
		END SIYO_091_ITA_FROM
		,CASE
			WHEN ITA091_CNT > 5 THEN ITA_091_TO
			ELSE ISNULL(NP_T_INPUT_ITAATSU_LOT_HEADER.SIYO_091_ITA_TO, KIJUN_091.DATA02)
		END SIYO_091_ITA_TO
		,NP_T_INPUT_ITAATSU_LOT_HEADER.GIJUTU_091
	FROM
		NP_T_INPUT_COMMON
	INNER JOIN (
		SELECT 
			LOT_NO
			,MAX(ID) ID 
		FROM
			NP_T_INPUT_COMMON
		WHERE
			PID = /**%PID%**/'' 
		GROUP BY LOT_NO ) A
		ON NP_T_INPUT_COMMON.ID = A.ID
	LEFT OUTER JOIN NP_T_INPUT_ITAATSU_LOT_HEADER
		ON NP_T_INPUT_ITAATSU_LOT_HEADER.LOT_NO = NP_T_INPUT_COMMON.LOT_NO

	INNER JOIN SIYOSYO_MAIN
		ON NP_T_INPUT_COMMON.HINMOKU_CD = SIYOSYO_MAIN.HINMOKU_CD
	OUTER APPLY(
		SELECT TOP 1
			KOUTEI_SEQ

		FROM
			KOUTEIJUN_KANRI
		WHERE
			SIYOSYO_SEQ = SIYOSYO_MAIN.SIYOSYO_SEQ
		AND KOUTEI_CD = '090'

	) KOUTEI_090

	OUTER APPLY (
		SELECT TOP 1
			KOUTEI_MEISAI_KOUMOKU.DATA01
			,KOUTEI_MEISAI_KOUMOKU.DATA02
		FROM
			KOUTEI_MEISAI_KOUMOKU
		WHERE 
			SIYOSYO_SEQ = SIYOSYO_MAIN.SIYOSYO_SEQ
		AND KOUTEI_SEQ = KOUTEI_090.KOUTEI_SEQ
		AND GYOUSU = '1'
	) KIJUN_090

	OUTER APPLY(
		SELECT TOP 1
			KOUTEI_SEQ

		FROM
			KOUTEIJUN_KANRI
		WHERE
			SIYOSYO_SEQ = SIYOSYO_MAIN.SIYOSYO_SEQ
		AND KOUTEI_CD = '091'

	) KOUTEI_091

	OUTER APPLY (
		SELECT TOP 1
			KOUTEI_MEISAI_KOUMOKU.DATA01
			,KOUTEI_MEISAI_KOUMOKU.DATA02
		FROM
			KOUTEI_MEISAI_KOUMOKU
		WHERE 
			SIYOSYO_SEQ = SIYOSYO_MAIN.SIYOSYO_SEQ
		AND KOUTEI_SEQ = KOUTEI_091.KOUTEI_SEQ
		AND GYOUSU = '1'
	) KIJUN_091

) TMP