-- 論理名: 部品原価期次累積VIEW
-- 旧VIEW: I1TBUHINGENKAKIJIRUISEKIVIEW  (ファイル: I1TBUHINGENKAKIJIRUISEKIVIEW.txt)
-- ベーステーブル: I1TBUHINGENKAKIJIRUISEKI -> tmh_acif_part_cost_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_part_cost_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.parts_number,
    a.outsource_product_date,
    a.management_number,
    a.combined_supply_type,
    a.product_type,
    a.external_sale_type,
    a.return_type,
    a.element_unit_price,
    a.parts_unit_price,
    a.processing_unit_price,
    a.element_amount,
    a.parts_amount,
    a.processing_amount,
    a.product_cost_process_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.created_by,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_part_cost_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_part_cost_cum_view IS '部品原価期次累積VIEW';

-- 論理名: 部品仕入期次累積VIEW
-- 旧VIEW: I1TBUHINSIREKIJIRUISEKIVIEW  (ファイル: I1TBUHINSIREKIJIRUISEKIVIEW.txt)
-- ベーステーブル: I1TBUHINSIIREKIJIRUISEKI -> tmh_acif_part_purchase_amount_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_part_purchase_amount_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.acceptance_date,
    a.delivery_note_number,
    a.parts_number,
    a.category,
    a.management_number,
    a.original_trading_partner_identifier,
    a.receipt_identifier,
    a.parts_system_type,
    a.mail_documentation_type,
    a.product_type,
    a.unchecked_type,
    a.retroactive_exclusion_type,
    a.check_carryover_type,
    b.print_order_type,
    a.toyota_shipment_department,
    a.external_sale_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_amount,
    b.debit_tax_type,
    b.debit_budget_identifier,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_tax_rate,
    b.credit_main_tax_type,
    b.credit_estimate_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.created_by,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.previous_quantity,
    b.previous_unit_price
FROM tmh_acif_part_purchase_amount_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_part_purchase_amount_cum_view IS '部品仕入期次累積VIEW';

-- 論理名: 部品たな卸金額期次累積VIEW
-- 旧VIEW: I1TBUHINTNORSAMTKIJIRISKVIEW  (ファイル: I1TBUHINTNORSAMTKIJIRISKVIEW.txt)
-- ベーステーブル: I1TBUHINTNORSAMTKIJIRUISEKI -> tmh_acif_part_inventory_amount_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_part_inventory_amount_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.parts_inventory_details_type,
    a.item_slip_type,
    a.department_identifier,
    a.inventory_type,
    a.product_instruction_mark,
    a.parts_number,
    a.group_identifier,
    a.receipt_identifier,
    a.address,
    a.object_number,
    a.seat_number,
    a.supplier_aviation_type,
    a.shelf_quantity,
    a.input_inventory_quantity,
    a.half_type,
    a.negative_conversion_type,
    a.uninput_type,
    a.element_cost_unit_price,
    a.element_amount,
    a.parts_cost_unit_price,
    a.parts_amount,
    a.all_process_cost_unit_price,
    a.all_process_amount,
    a.current_process_cost_unit_price,
    a.current_process_amount,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_part_inventory_amount_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_part_inventory_amount_cum_view IS '部品たな卸金額期次累積VIEW';

-- 論理名: 部品売上期次累積VIEW
-- 旧VIEW: I1TBUHINURIAGEKIJIRISKVIEW  (ファイル: I1TBUHINURIAGEKIJIRISKVIEW.txt)
-- ベーステーブル: I1TBUHINURIAGEKIJIRUISEKI -> tmh_acif_part_sales_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_part_sales_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.shipment_date,
    a.delivery_note_number,
    a.parts_number,
    a.management_number,
    a.slip_type AS sales_slip_type,
    a.combined_supply_type,
    a.product_type,
    a.external_sale_type,
    a.kd_type,
    a.return_additional_entry_type,
    a.partial_delivery_type,
    a.unchecked_type,
    a.retroactive_exclusion_type,
    a.check_carryover_type,
    b.print_order_type,
    a.destination_identifier,
    a.delivery_plan_date,
    a.tmc_acceptance_date,
    a.offset_billing_type,
    b.selected_cost_process_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type AS journal_slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_amount,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_tax_rate,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at AS journal_timestamp,
    b.created_by AS journal_created_by,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.previous_quantity,
    b.previous_unit_price
FROM tmh_acif_part_sales_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_part_sales_cum_view IS '部品売上期次累積VIEW';

-- 論理名: 部品製造原価期次累積VIEW
-- 旧VIEW: I1TDWHBHNSIZGENKAKIJIRISKVIEW  (ファイル: I1TDWHBHNSIZGENKAKIJIRISKVIEW.txt)
-- ベーステーブル: I1TDWHBUHINGENKAKIJIRUISEKI -> tmh_acif_part_cost_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_part_cost_cum_dwh_manufacturing_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.parts_number,
    a.parts_name,
    a.outsource_product_date,
    a.management_number,
    a.combined_supply_type,
    a.product_type,
    a.external_sale_type,
    a.return_type,
    a.element_unit_price,
    a.parts_unit_price,
    a.processing_unit_price,
    a.element_amount,
    a.parts_amount,
    a.processing_amount,
    a.product_cost_process_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_part_cost_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '08'
;
COMMENT ON VIEW tmh_acif_part_cost_cum_dwh_manufacturing_view IS '部品製造原価期次累積VIEW';

-- 論理名: 部品売上原価期次累積VIEW
-- 旧VIEW: I1TDWHBHNURIGENKAKIJIRISKVIEW  (ファイル: I1TDWHBHNURIGENKAKIJIRISKVIEW.txt)
-- ベーステーブル: I1TDWHBUHINGENKAKIJIRUISEKI -> tmh_acif_part_cost_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_part_cost_cum_dwh_sales_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.parts_number,
    a.parts_name,
    a.outsource_product_date,
    a.management_number,
    a.combined_supply_type,
    a.product_type,
    a.external_sale_type,
    a.return_type,
    a.element_unit_price,
    a.parts_unit_price,
    a.processing_unit_price,
    a.element_amount,
    a.parts_amount,
    a.processing_amount,
    a.product_cost_process_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_part_cost_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '07'
;
COMMENT ON VIEW tmh_acif_part_cost_cum_dwh_sales_view IS '部品売上原価期次累積VIEW';

-- 論理名: （DWH）部品仕入期次累積VIEW
-- 旧VIEW: I1TDWHBUHINSIREKIJIRISKIVIEW  (ファイル: I1TDWHBUHINSIREKIJIRISKIVIEW.txt)
-- ベーステーブル: I1TDWHBUHINSIREKIJIRUISEKI -> tmh_acif_part_purchase_amount_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_part_purchase_amount_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.acceptance_date,
    a.delivery_note_number,
    a.parts_number,
    a.parts_name,
    a.category,
    a.management_number,
    a.original_trading_partner_identifier,
    a.original_trading_partner_name,
    a.receipt_identifier,
    a.parts_system_type,
    a.mail_documentation_type,
    a.product_type,
    a.unchecked_type,
    a.retroactive_exclusion_type,
    a.check_carryover_type,
    b.print_order_type,
    a.toyota_shipment_department,
    a.external_sale_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_amount,
    b.debit_tax_type,
    b.debit_budget_identifier,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_tax_rate,
    b.credit_main_tax_type,
    b.credit_estimate_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.previous_quantity,
    b.previous_unit_price
FROM tmh_acif_part_purchase_amount_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '05'
;
COMMENT ON VIEW tmh_acif_part_purchase_amount_cum_dwh_view IS '（DWH）部品仕入期次累積VIEW';

-- 論理名: （DWH）部品たな卸金額期次累積VIEW
-- 旧VIEW: I1TDWHBUHINTNORSAMTKJRISKVIEW  (ファイル: I1TDWHBUHINTNORSAMTKJRISKVIEW.txt)
-- ベーステーブル: I1TDWHBUHINTNORSAMTKIJIRISK -> tmh_acif_part_inventory_amount_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_part_inventory_amount_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.parts_inventory_details_type,
    a.item_slip_type,
    a.department_identifier,
    a.inventory_type,
    a.product_instruction_mark,
    a.parts_number,
    a.parts_name,
    a.group_identifier,
    a.receipt_identifier,
    a.address,
    a.object_number,
    a.seat_number,
    a.supplier_aviation_type,
    a.shelf_quantity,
    a.input_inventory_quantity,
    a.half_type,
    a.negative_conversion_type,
    a.uninput_type,
    a.element_cost_unit_price,
    a.element_amount,
    a.parts_cost_unit_price,
    a.parts_amount,
    a.all_process_cost_unit_price,
    a.all_process_amount,
    a.current_process_cost_unit_price,
    a.current_process_amount,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_part_inventory_amount_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier in ('52','53')
;
COMMENT ON VIEW tmh_acif_part_inventory_amount_cum_dwh_view IS '（DWH）部品たな卸金額期次累積VIEW';

-- 論理名: （DWH）部品売上期次累積VIEW
-- 旧VIEW: I1TDWHBUHINURIAGKIJIRISKIVIEW  (ファイル: I1TDWHBUHINURIAGKIJIRISKIVIEW.txt)
-- ベーステーブル: I1TDWHBUHINURIAGEKIJIRUISEKI -> tmh_acif_part_sales_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_part_sales_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.shipment_date,
    a.delivery_note_number,
    a.parts_number,
    a.parts_name,
    a.management_number,
    a.slip_type,
    a.combined_supply_type,
    a.product_type,
    a.external_sale_type,
    a.kd_type,
    a.return_additional_entry_type,
    a.partial_delivery_type,
    a.unchecked_type,
    a.retroactive_exclusion_type,
    a.check_carryover_type,
    b.print_order_type,
    a.destination_identifier,
    a.delivery_plan_date,
    a.tmc_acceptance_date,
    a.offset_billing_type,
    b.selected_cost_process_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type AS journal_slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_amount,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_tax_rate,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.previous_quantity,
    b.previous_unit_price
FROM tmh_acif_part_sales_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '06'
;
COMMENT ON VIEW tmh_acif_part_sales_cum_dwh_view IS '（DWH）部品売上期次累積VIEW';

-- 論理名: （DWH）加工不良金額期次累積VIEW
-- 旧VIEW: I1TDWHKAKOUFURYOUKIJIRISKVIEW  (ファイル: I1TDWHKAKOUFURYOUKIJIRISKVIEW.txt)
-- ベーステーブル: I1TDWHKAKOUFURYOUKIJIRUISEKI -> tmh_acif_processing_defect_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_processing_defect_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.department,
    a.parts_number,
    a.parts_name,
    a.journal_pattern,
    a.journal_pattern_number,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_processing_defect_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '14'
;
COMMENT ON VIEW tmh_acif_processing_defect_cum_dwh_view IS '（DWH）加工不良金額期次累積VIEW';

-- 論理名: （DWH）給与実績期次累積VIEW
-- 旧VIEW: I1TDWHKYUUYOJISSEKIKJRISKVIEW  (ファイル: I1TDWHKYUUYOJISSEKIKJRISKVIEW.txt)
-- ベーステーブル: I1TDWHKYUUYOJISSEKIKIJIRUISEKI -> tmh_acif_payroll_payment_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_payroll_payment_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.salary_bonus_type,
    a.provision_date,
    a.estimate_confirmed_type,
    a.current_month_affiliation_identifier,
    a.previous_month_position_identifier,
    a.employee_type,
    a.supply_deduction_type,
    a.account_item_identifier,
    a.system_item_identifier,
    a.tax_amount,
    a.journal_expense_type,
    a.red_black_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_amount,
    b.debit_budget_identifier,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_tax_rate,
    b.credit_estimate_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_payroll_payment_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '11'
;
COMMENT ON VIEW tmh_acif_payroll_payment_cum_dwh_view IS '（DWH）給与実績期次累積VIEW';

-- 論理名: （DWH）納番変換期次累積VIEW
-- 旧VIEW: I1TDWHNOUBANHENKANKJRISKVIEW  (ファイル: I1TDWHNOUBANHENKANKJRISKVIEW.txt)
-- ベーステーブル: I1TDWHNOUBANHENKANKIJIRISK -> tmh_acif_delivery_number_conversion_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_delivery_number_conversion_cum_dwh_view AS
SELECT
    a.created_company_identifier,
    a.created_by,
    a.created_process_identifier,
    a.created_ip_address,
    a.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.registration_year_month,
    a.parts_number,
    a.parts_name,
    a.management_number,
    a.delivery_note_number,
    a.check_delivery_note_number
FROM tmh_acif_delivery_number_conversion_cum_dwh a
;
COMMENT ON VIEW tmh_acif_delivery_number_conversion_cum_dwh_view IS '（DWH）納番変換期次累積VIEW';

-- 論理名: （DWH）照合データ期次累積VIEW
-- 旧VIEW: I1TDWHSHOGODATAKIJIRISKIVIEW  (ファイル: I1TDWHSHOGODATAKIJIRISKIVIEW.txt)
-- ベーステーブル: I1TDWHSHOGODATAKIJIRUISEKI -> tmh_acif_reconciliation_line_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_reconciliation_line_cum_dwh_view AS
SELECT
    a.created_company_identifier,
    a.created_by,
    a.created_process_identifier,
    a.created_ip_address,
    a.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.matching_date,
    a.matching_type,
    a.parts_number,
    a.parts_name,
    a.management_number,
    a.check_delivery_order_number,
    a.retroactive_check_delivery_order_number,
    a.slip_type,
    a.retroactive_details_type,
    a.combined_supply_type,
    a.original_trading_partner_identifier,
    a.original_trading_partner_name,
    a.issue_destination,
    a.accounting_setting_type,
    a.tmc_configuration_type,
    a.accounting_cumulative_number,
    a.accounting_cumulative_data_identifier,
    a.accounting_delivery_order_number,
    a.partial_delivery_type,
    a.accounting_recorded_date,
    a.accounting_acceptance_date,
    a.accounting_issue_date,
    a.accounting_entry_scheduled_date,
    a.accounting_quantity,
    a.accounting_unit_price,
    a.accounting_amount,
    a.tmc_received_date_number,
    a.tmc_acceptance_date,
    a.tmc_quantity,
    a.tmc_unit_price,
    a.tmc_amount,
    a.tmc_retroactive_unit_price,
    a.tmc_retroactive_amount,
    a.tmc_delivery_order_number,
    a.tmc_debit_credit_type,
    a.tmc_trading_partner_identifier,
    a.tmc_partial_delivery_type,
    a.tmc_correction_presence_type,
    a.tmc_retroactive_presence_type,
    a.toyota_unit_price,
    a.toyota_amount,
    a.check_result,
    a.check_carryover_type,
    a.previous_month_reference_carryover_type
FROM tmh_acif_reconciliation_line_cum_dwh a
;
COMMENT ON VIEW tmh_acif_reconciliation_line_cum_dwh_view IS '（DWH）照合データ期次累積VIEW';

-- 論理名: （DWH）仕掛品出庫期次累積VIEW
-- 旧VIEW: I1TDWHSIKAKARSYUKKOKJRISKVIEW  (ファイル: I1TDWHSIKAKARSYUKKOKJRISKVIEW.txt)
-- ベーステーブル: I1TDWHSIKAKARISYUKKOKIJIRISK -> tmh_acif_wip_issue_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_wip_issue_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.parts_number,
    a.parts_name,
    a.issue_date,
    a.delivery_note_number,
    a.management_number,
    a.issue_destination,
    a.pre_issue_department,
    a.financial_type,
    a.model_tool_number,
    a.check_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.debit_budget_identifier,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.credit_estimate_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_wip_issue_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '12'
;
COMMENT ON VIEW tmh_acif_wip_issue_cum_dwh_view IS '（DWH）仕掛品出庫期次累積VIEW';

-- 論理名: （DWH）資材原価期次累積VIEW
-- 旧VIEW: I1TDWHSIZAIGENKAKIJIRISKIVIEW  (ファイル: I1TDWHSIZAIGENKAKIJIRISKIVIEW.txt)
-- ベーステーブル: I1TDWHSIZAIGENKAKIJIRUISEKI -> tmh_acif_item_cogs_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_item_cogs_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.item_select_identifier,
    a.item_select_name,
    a.shipment_date,
    a.delivery_note_number,
    a.selection_type,
    a.unchecked_type,
    a.retroactive_exclusion_type,
    a.journal_pattern,
    a.journal_pattern_number,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type,
    b.previous_quantity,
    b.previous_unit_price
FROM tmh_acif_item_cogs_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '04'
;
COMMENT ON VIEW tmh_acif_item_cogs_cum_dwh_view IS '（DWH）資材原価期次累積VIEW';

-- 論理名: （DWH）資材仕入期次累積VIEW
-- 旧VIEW: I1TDWHSIZAISIIREKIJIRISKIVIEW  (ファイル: I1TDWHSIZAISIIREKIJIRISKIVIEW.txt)
-- ベーステーブル: I1TDWHSIZAISIIREKIJIRUISEKI -> tmh_acif_item_purchase_amount_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_item_purchase_amount_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.acceptance_date,
    a.delivery_note_number,
    a.parts_number,
    a.parts_name,
    a.management_number,
    a.original_trading_partner_identifier,
    a.original_trading_partner_name,
    b.trading_partner_identifier,
    b.partner_name,
    a.self_supply_type,
    a.return_type,
    a.internal_type,
    a.settlement_type,
    a.special_order_repair_type,
    a.unchecked_type,
    a.retroactive_exclusion_type,
    a.via_route_type,
    a.tmc_inventory_settlement_type,
    b.print_order_type,
    a.diesel_tax_per_liter,
    a.model_tool_number,
    a.receipt_warehouse_identifier,
    a.warehousing_date,
    b.correct_reason_type,
    b.correction_reason,
    a.main_cumulative_number,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_amount,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_tax_rate,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.previous_quantity,
    b.previous_unit_price
FROM tmh_acif_item_purchase_amount_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '01'
;
COMMENT ON VIEW tmh_acif_item_purchase_amount_cum_dwh_view IS '（DWH）資材仕入期次累積VIEW';

-- 論理名: （DWH）資材出庫期次累積VIEW
-- 旧VIEW: I1TDWHSIZAISYUKKOKJRISKIVIEW  (ファイル: I1TDWHSIZAISYUKKOKJRISKIVIEW.txt)
-- ベーステーブル: I1TDWHSIZAISYUKKOKIJIRUISEKI -> tmh_acif_item_issue_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_item_issue_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.delivery_note_number,
    a.parts_number,
    a.parts_name,
    a.management_number,
    a.issue_destination,
    a.supply_recipient_identifier,
    a.issue_group,
    a.secondhand_type,
    a.settlement_type,
    a.issue_difference_type,
    a.financial_type,
    a.issue_item,
    a.reacceptance_type,
    a.reacceptance_return_issue_type,
    a.model_tool_number,
    a.issue_warehouse_identifier,
    a.issue_date,
    a.period_number,
    a.employee_name,
    a.unit_price_undecided_error_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.debit_budget_identifier,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.credit_estimate_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_item_issue_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier in ('02','50')
;
COMMENT ON VIEW tmh_acif_item_issue_cum_dwh_view IS '（DWH）資材出庫期次累積VIEW';

-- 論理名: （DWH）資材たな卸金額期次累積VIEW
-- 旧VIEW: I1TDWHSIZAITNORSAMTKJRISKVIEW  (ファイル: I1TDWHSIZAITNORSAMTKJRISKVIEW.txt)
-- ベーステーブル: I1TDWHSIZAITNORSAMTKIJIRISK -> tmh_acif_item_inventory_amount_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_item_inventory_amount_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.material_inventory_details_type,
    a.item_slip_type,
    a.source_info_type,
    a.department,
    a.parts_number,
    a.parts_name,
    a.warehouse_identifier,
    a.consumable_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.credit_identifier,
    b.credit_name,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_item_inventory_amount_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier in ('54','55')
;
COMMENT ON VIEW tmh_acif_item_inventory_amount_cum_dwh_view IS '（DWH）資材たな卸金額期次累積VIEW';

-- 論理名: （DWH）資材売上期次累積VIEW
-- 旧VIEW: I1TDWHSIZAIURIAGEKIJIRISKVIEW  (ファイル: I1TDWHSIZAIURIAGEKIJIRISKVIEW.txt)
-- ベーステーブル: I1TDWHSIZAIURIAGEKIJIRUISEKI -> tmh_acif_item_sales_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_item_sales_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.shipment_date,
    a.delivery_note_number,
    a.item_select_identifier,
    a.item_select_name,
    a.journal_pattern,
    a.unchecked_type,
    a.retroactive_exclusion_type,
    a.measurement_category,
    b.print_order_type,
    a.model_tool_number,
    a.car_number,
    a.offset_billing_type,
    a.request_number,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_amount,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_tax_rate,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.previous_quantity,
    b.previous_unit_price
FROM tmh_acif_item_sales_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '03'
;
COMMENT ON VIEW tmh_acif_item_sales_cum_dwh_view IS '（DWH）資材売上期次累積VIEW';

-- 論理名: （DWH）特調たな卸金額期次累積VIEW
-- 旧VIEW: I1TDWHTKCHOTNORSAMTKJRISKVIEW  (ファイル: I1TDWHTKCHOTNORSAMTKJRISKVIEW.txt)
-- ベーステーブル: I1TDWHTOKUCHOTNORSAMTKIJIRISK -> tmh_acif_specific_procurement_inventory_amount_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_specific_procurement_inventory_amount_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.management_number,
    a.inventory_execution_department,
    a.procurement_subject_name,
    a.acceptance_date,
    a.burden_department,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_specific_procurement_inventory_amount_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '51'
;
COMMENT ON VIEW tmh_acif_specific_procurement_inventory_amount_cum_dwh_view IS '（DWH）特調たな卸金額期次累積VIEW';

-- 論理名: （DWH）TMC受信データ期次累積VIEW
-- 旧VIEW: I1TDWHTMCJYUSINDATAKJRISKVIEW  (ファイル: I1TDWHTMCJYUSINDATAKJRISKVIEW.txt)
-- ベーステーブル: I1TDWHTMCJYUSINDATAKIJIRISK -> tmh_acif_tmc_received_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_tmc_received_cum_dwh_view AS
SELECT
    a.created_company_identifier,
    a.created_by,
    a.created_process_identifier,
    a.created_ip_address,
    a.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.receive_date_number,
    a.matching_date,
    a.received_details_type,
    a.matching_receivable_payable_type,
    a.layout_type,
    a.dt_identifier,
    a.transfer_number,
    a.card_number,
    a.trading_partner_identifier,
    a.partner_name,
    a.parts_number,
    a.parts_name,
    a.category,
    a.management_number,
    a.delivery_note_number,
    a.debit_credit_type,
    a.quantity,
    a.unit_price,
    a.amount,
    a.receipt_year,
    a.receipt_month,
    a.receipt_date,
    a.issue_destination,
    a.provisional_settlement_correction_identifier,
    a.check_group_number,
    a.slip_type,
    a.check_delivery_order_number,
    a.retroactive_check_delivery_order_number,
    a.tmc_partial_delivery_type,
    a.correction_existing_type,
    a.combined_supply_type,
    a.acceptance_date,
    a.check_quantity,
    a.check_unit_price,
    a.check_amount,
    a.retroactive_unit_price,
    a.retroactive_amount,
    a.current_month_retroactive_unit_price,
    a.current_month_retroactive_amount,
    a.unchecked_type,
    a.retroactive_details_type,
    a.carryover_type
FROM tmh_acif_tmc_received_cum_dwh a
;
COMMENT ON VIEW tmh_acif_tmc_received_cum_dwh_view IS '（DWH）TMC受信データ期次累積VIEW';

-- 論理名: （DWH）特調仕入期次累積VIEW
-- 旧VIEW: I1TDWHTOKUCHOSIREKIJIRISKVIEW  (ファイル: I1TDWHTOKUCHOSIREKIJIRISKVIEW.txt)
-- ベーステーブル: I1TDWHTOKUCHOSIREKIJIRUISEKI -> tmh_acif_specific_procurement_purchase_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_specific_procurement_purchase_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.acceptance_date,
    a.delivery_note_number,
    a.management_number,
    a.internal_type,
    a.internal_department,
    a.tmc_supply_type,
    a.requesting_department,
    a.procurement_subject_name,
    a.financial_type,
    a.hnt_type,
    a.delivery_date,
    a.procurement_person_in_charge,
    b.correct_reason_type,
    b.correction_reason,
    b.unit_price_undecided_error_type,
    b.reunit_matching_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_amount,
    b.debit_tax_type,
    b.debit_budget_identifier,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_tax_rate,
    b.credit_main_tax_type,
    b.credit_estimate_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.print_order_type,
    b.previous_quantity,
    b.previous_unit_price
FROM tmh_acif_specific_procurement_purchase_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '09'
;
COMMENT ON VIEW tmh_acif_specific_procurement_purchase_cum_dwh_view IS '（DWH）特調仕入期次累積VIEW';

-- 論理名: （DWH）特定加工費期次累積VIEW
-- 旧VIEW: I1TDWHTOKUTEIKAKOHIKJRISKVIEW  (ファイル: I1TDWHTOKUTEIKAKOHIKJRISKVIEW.txt)
-- ベーステーブル: I1TDWHTOKUTEIKAKOUHIKIJIRISK -> tmh_acif_specific_processing_cost_cum_dwh, I1TDWHSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum_dwh
CREATE OR REPLACE VIEW tmh_acif_specific_processing_cost_cum_dwh_view AS
SELECT
    b.created_company_identifier,
    b.created_by,
    b.created_process_identifier,
    b.created_ip_address,
    b.created_at,
    a.updated_company_identifier,
    a.updated_by,
    a.updated_process_identifier,
    a.updated_ip_address,
    a.updated_at,
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.management_number,
    a.executing_department,
    a.specific_labor_hours,
    a.rate,
    a.specific_amount,
    a.procurement_subject_name,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.partner_name,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_name,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_name,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_specific_processing_cost_cum_dwh a
JOIN tmh_acif_journal_entry_cum_dwh b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE b.cumulative_data_identifier = '13'
;
COMMENT ON VIEW tmh_acif_specific_processing_cost_cum_dwh_view IS '（DWH）特定加工費期次累積VIEW';

-- 論理名: 加工不良金額期次累積VIEW
-- 旧VIEW: I1TKAKOUFURYOUKIJIRUISEKIVIEW  (ファイル: I1TKAKOUFURYOUKIJIRUISEKIVIEW.txt)
-- ベーステーブル: I1TKAKOUFURYOUKIJIRISKI -> tmh_acif_processing_defect_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_processing_defect_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.department,
    a.parts_number,
    a.journal_pattern,
    a.journal_pattern_number,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.interface_receivable_payable_journal_number,
    b.created_by,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_processing_defect_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_processing_defect_cum_view IS '加工不良金額期次累積VIEW';

-- 論理名: 給与実績期次累積VIEW
-- 旧VIEW: I1TKYUUYOJISSEKIKIJIRISKVIEW  (ファイル: I1TKYUUYOJISSEKIKIJIRISKVIEW.txt)
-- ベーステーブル: I1TKYUUYOJISSEKIKIJIRISKI -> tmh_acif_payroll_payment_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_payroll_payment_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.salary_bonus_type,
    a.provision_date,
    a.estimate_confirmed_type,
    a.current_month_affiliation_identifier,
    a.previous_month_position_identifier,
    a.employee_type,
    a.supply_deduction_type,
    a.account_item_identifier,
    a.system_item_identifier,
    a.tax_amount,
    a.journal_expense_type,
    a.red_black_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_amount,
    b.debit_budget_identifier,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_tax_rate,
    b.credit_estimate_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_payroll_payment_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_payroll_payment_cum_view IS '給与実績期次累積VIEW';

-- 論理名: 仕掛品出庫期次累積VIEW
-- 旧VIEW: I1TSIKAKARISYKKKIJIRUISEKIVIEW  (ファイル: I1TSIKAKARISYKKKIJIRUISEKIVIEW.txt)
-- ベーステーブル: I1TSIKAKARISYUKKOKIJIRUISEKI -> tmh_acif_wip_issue_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_wip_issue_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.parts_number,
    a.issue_date,
    a.delivery_note_number,
    a.management_number,
    a.issue_destination,
    a.pre_issue_department,
    a.financial_type,
    a.model_tool_number,
    a.check_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.debit_budget_identifier,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.credit_estimate_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.created_by,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_wip_issue_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_wip_issue_cum_view IS '仕掛品出庫期次累積VIEW';

-- 論理名: 資材売上原価期次累積VIEW
-- 旧VIEW: I1TSIZAIGENKAKIJIRUISEKIVIEW  (ファイル: I1TSIZAIGENKAKIJIRUISEKIVIEW.txt)
-- ベーステーブル: I1TSIZAIGENKAKIJIRUISEKI -> tmh_acif_item_cogs_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_item_cogs_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.item_select_identifier,
    a.shipment_date,
    a.delivery_note_number,
    a.selection_type,
    a.unchecked_type,
    a.retroactive_exclusion_type,
    a.journal_pattern,
    a.journal_pattern_number,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.created_by,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type,
    b.previous_quantity,
    b.previous_unit_price
FROM tmh_acif_item_cogs_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_item_cogs_cum_view IS '資材売上原価期次累積VIEW';

-- 論理名: 資材仕入期次累積VIEW
-- 旧VIEW: I1TSIZAISIIREKIJIRUISEKIVIEW  (ファイル: I1TSIZAISIIREKIJIRUISEKIVIEW.txt)
-- ベーステーブル: I1TSIZAISIIREKIJIRUISEKI -> tmh_acif_item_purchase_amount_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_item_purchase_amount_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.acceptance_date,
    a.delivery_note_number,
    a.parts_number,
    a.management_number,
    a.original_trading_partner_identifier,
    b.trading_partner_identifier,
    a.self_supply_type,
    a.return_type,
    a.internal_type,
    a.settlement_type,
    a.special_order_repair_type,
    a.unchecked_type,
    a.retroactive_exclusion_type,
    a.via_route_type,
    a.tmc_inventory_settlement_type,
    b.print_order_type,
    a.diesel_tax_per_liter,
    a.model_tool_number,
    a.receipt_warehouse_identifier,
    a.warehousing_date,
    b.correct_reason_type,
    b.correction_reason,
    a.main_cumulative_number,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_amount,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_tax_rate,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.created_by,
    b.created_at,
    b.interface_receivable_payable_journal_number,
    b.previous_quantity,
    b.previous_unit_price
FROM tmh_acif_item_purchase_amount_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_item_purchase_amount_cum_view IS '資材仕入期次累積VIEW';

-- 論理名: 資材出庫期次累積VIEW
-- 旧VIEW: I1TSIZAISYUKKOKIJIRUISEKIVIEW  (ファイル: I1TSIZAISYUKKOKIJIRUISEKIVIEW.txt)
-- ベーステーブル: I1TSIZAISYUKKOKIJIRUISEKI -> tmh_acif_item_issue_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_item_issue_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.delivery_note_number,
    a.parts_number,
    a.management_number,
    a.issue_destination,
    a.supply_recipient_identifier,
    a.issue_group,
    a.secondhand_type,
    a.settlement_type,
    a.issue_difference_type,
    a.financial_type,
    a.issue_item,
    a.reacceptance_type,
    a.reacceptance_return_issue_type,
    a.model_tool_number,
    a.issue_warehouse_identifier,
    a.issue_date,
    a.period_number,
    a.employee_name,
    a.unit_price_undecided_error_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.debit_budget_identifier,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.credit_estimate_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.created_by,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_item_issue_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE a.issue_difference_type = '0'
;
COMMENT ON VIEW tmh_acif_item_issue_cum_view IS '資材出庫期次累積VIEW';

-- 論理名: 資材出庫差額期次累積VIEW
-- 旧VIEW: I1TSIZAISYUKKOSGKKIJIRISKVIEW  (ファイル: I1TSIZAISYUKKOSGKKIJIRISKVIEW.txt)
-- ベーステーブル: I1TSIZAISYUKKOKIJIRUISEKI -> tmh_acif_item_issue_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_item_issue_cum_diff_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.delivery_note_number,
    a.parts_number,
    a.management_number,
    a.issue_destination,
    a.supply_recipient_identifier,
    a.issue_group,
    a.secondhand_type,
    a.settlement_type,
    a.issue_difference_type,
    a.financial_type,
    a.issue_item,
    a.reacceptance_type,
    a.reacceptance_return_issue_type,
    a.model_tool_number,
    a.issue_warehouse_identifier,
    a.issue_date,
    a.period_number,
    a.employee_name,
    a.unit_price_undecided_error_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.debit_budget_identifier,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.credit_estimate_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_item_issue_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
WHERE a.issue_difference_type = '1'
;
COMMENT ON VIEW tmh_acif_item_issue_cum_diff_view IS '資材出庫差額期次累積VIEW';

-- 論理名: 資材たな卸金額期次累積VIEW
-- 旧VIEW: I1TSIZAITNORSAMTKIJIRISKVIEW  (ファイル: I1TSIZAITNORSAMTKIJIRISKVIEW.txt)
-- ベーステーブル: I1TSIZAITNORSAMTKIJIRUISEKI -> tmh_acif_item_inventory_amount_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_item_inventory_amount_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.material_inventory_details_type,
    a.item_slip_type,
    a.source_info_type,
    a.department,
    a.parts_number,
    a.warehouse_identifier,
    a.consumable_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.credit_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_item_inventory_amount_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_item_inventory_amount_cum_view IS '資材たな卸金額期次累積VIEW';

-- 論理名: 資材売上期次累積VIEW
-- 旧VIEW: I1TSIZAIURIAGEKIJIRUISEKIVIEW  (ファイル: I1TSIZAIURIAGEKIJIRUISEKIVIEW.txt)
-- ベーステーブル: I1TSIZAIURIAGEKIJIRUISEKI -> tmh_acif_item_sales_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_item_sales_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.shipment_date,
    a.delivery_note_number,
    a.item_select_identifier,
    a.journal_pattern,
    a.unchecked_type,
    a.retroactive_exclusion_type,
    a.measurement_category,
    b.print_order_type,
    a.model_tool_number,
    a.car_number,
    a.offset_billing_type,
    a.request_number,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_amount,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_tax_rate,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.created_by,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.previous_quantity,
    b.previous_unit_price
FROM tmh_acif_item_sales_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_item_sales_cum_view IS '資材売上期次累積VIEW';

-- 論理名: 特調たな卸金額期次累積VIEW
-- 旧VIEW: I1TTOKCHOTNORSAMTKIJIRISKVIEW  (ファイル: I1TTOKCHOTNORSAMTKIJIRISKVIEW.txt)
-- ベーステーブル: I1TTOKUCHOTNORSAMTKIJIRUISEKI -> tmh_acif_specific_procurement_inventory_amount_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_specific_procurement_inventory_amount_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.management_number,
    a.inventory_execution_department,
    a.procurement_subject_name,
    a.acceptance_date,
    a.burden_department,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.credit_identifier,
    b.credit_burden_department,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_specific_procurement_inventory_amount_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_specific_procurement_inventory_amount_cum_view IS '特調たな卸金額期次累積VIEW';

-- 論理名: 特調仕入期次累積VIEW
-- 旧VIEW: I1TTOKUCHOSIREKIJIRUISEKIVIEW  (ファイル: I1TTOKUCHOSIREKIJIRUISEKIVIEW.txt)
-- ベーステーブル: I1TTOKUCHOSIIREKIJIRUISEKI -> tmh_acif_specific_procurement_purchase_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_specific_procurement_purchase_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.acceptance_date,
    a.delivery_note_number,
    a.management_number,
    a.internal_type,
    a.internal_department,
    a.tmc_supply_type,
    a.requesting_department,
    a.procurement_subject_name,
    a.financial_type,
    a.hnt_type,
    a.delivery_date,
    a.procurement_person_in_charge,
    b.correct_reason_type,
    b.correction_reason,
    b.unit_price_undecided_error_type,
    b.reunit_matching_type,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_amount,
    b.debit_tax_type,
    b.debit_budget_identifier,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_tax_rate,
    b.credit_main_tax_type,
    b.credit_estimate_identifier,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.created_by,
    b.interface_receivable_payable_journal_number,
    b.print_order_type,
    b.previous_quantity,
    b.previous_unit_price
FROM tmh_acif_specific_procurement_purchase_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_specific_procurement_purchase_cum_view IS '特調仕入期次累積VIEW';

-- 論理名: 特定加工費期次累積VIEW
-- 旧VIEW: I1TTOKUTEIKAKOUKIJIRUISEKIVIEW  (ファイル: I1TTOKUTEIKAKOUKIJIRUISEKIVIEW.txt)
-- ベーステーブル: I1TTOKUTEIKAKOUHIKIJIRUISEKI -> tmh_acif_specific_processing_cost_cum, I1TSIWAKEJOUHOUKIJIRUISEKI -> tmh_acif_journal_entry_cum
CREATE OR REPLACE VIEW tmh_acif_specific_processing_cost_cum_view AS
SELECT
    a.company_identifier,
    a.cumulative_number,
    b.cumulative_detail_number,
    a.management_number,
    a.executing_department,
    a.specific_labor_hours,
    a.rate,
    a.specific_amount,
    a.procurement_subject_name,
    b.cumulative_data_identifier,
    b.recorded_date,
    b.system_type,
    b.slip_type,
    b.trading_partner_identifier,
    b.unit,
    b.quantity,
    b.unit_price,
    b.amount,
    b.debit_identifier,
    b.debit_burden_department,
    b.debit_tax_process_identifier,
    b.debit_tax_input_type,
    b.debit_tax_type,
    b.credit_identifier,
    b.credit_burden_department,
    b.credit_tax_process_identifier,
    b.credit_tax_input_type,
    b.credit_main_tax_type,
    b.issue_serial_number,
    b.journal_entry_interface_create_type,
    b.outline_identifier,
    b.outline_name,
    b.reversal_shipment_plan_date,
    b.process_state,
    b.slip_type_identifier,
    b.interface_journal_number,
    b.updated_at,
    b.interface_receivable_payable_journal_number,
    b.correct_reason_type,
    b.correction_reason,
    b.print_order_type
FROM tmh_acif_specific_processing_cost_cum a
JOIN tmh_acif_journal_entry_cum b ON a.company_identifier = b.company_identifier
    AND a.cumulative_number = b.cumulative_number
;
COMMENT ON VIEW tmh_acif_specific_processing_cost_cum_view IS '特定加工費期次累積VIEW';