SELECT
	SIYOSYO_SEQ -- PK HIDDEN
	,KOUTEI_SEQ -- PK HIDDEN
	,DATA0001 -- 重ね
	,TOKUSYU_JOKEN00 -- 特殊条件(1行目)
	,DATA0101 -- ミニバイア
	,TOKUSYU_JOKEN01 -- 特殊条件(2行目)
	,DATA0201 -- PRG
	,TOKUSYU_JOKEN02 -- 特殊条件(3行目)
	,DATA0301 -- 明細
	,TOKUSYU_JOKEN03 -- 特殊条件(4行目)
	,DATA0401 -- F/D
	,TOKUSYU_JOKEN04 -- 特殊条件(5行目)
	,DATA0501 -- ラック立て
	,TOKUSYU_JOKEN05 -- 特殊条件(6行目)
	,CREATED_BY
	,CREATED_PRG_NM
	,CREATED_DATE
	,UPDATED_BY
	,UPDATED_PRG_NM
	,UPDATED_DATE
	,MODIFY_COUNT
FROM
	SIYO_SEIZO_JKN_HEADER